/* WaddleRush browser preview: self-contained, offline, no network calls. */
(() => {
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
  const menu=document.querySelector('#menu'),hud=document.querySelector('#hud'),results=document.querySelector('#results');
  const stats=document.querySelector('#stats'),board=document.querySelector('#board'),summary=document.querySelector('#summary');
  const play=document.querySelector('#play'),again=document.querySelector('#again'),home=document.querySelector('#home'),boostButton=document.querySelector('#boost');
  const NAMES=['IceKing','FishHunter','SnowByte','PinguPro','Frosty','WaddleBoss','Chilly','Aurora','IceBlade','SnowStorm','GlacierFox','PolarPop','KrillBill','BlueFlipper','SleetFeet','IglooGuru','TundraDash','ArcticAce'];
  let w=0,h=0,dpr=1,live=false,last=0,time=0,left=120,player,bots,fish,input={x:0,y:0,on:false,boost:false},ranks=[];
  const R=()=>Math.random(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  function resize(){dpr=devicePixelRatio||1;w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
  function unit(t=1){return {tier:t,mass:t,space:t===1?15:t===3?22:31}}
  function colony(name,playerFlag,x,y,color){let c={name,player:playerFlag,x,y,a:R()*Math.PI*2,target:0,units:[unit(),unit(),unit()],trail:[],color,fish:0,crops:0,fusions:0,big:0,immune:0,brain:R()*1.4+.6,think:0};for(let i=0;i<100;i++)c.trail.push({x:x-Math.cos(c.a)*i*.7,y:y-Math.sin(c.a)*i*.7});return c}
  function mass(c){return c.units.reduce((n,u)=>n+u.mass,0)}
  function reset(){left=120;time=0;fish=[];bots=[];player=colony('PLAYER',true,0,0,'#50efff');for(let i=0;i<17;i++){let a=R()*Math.PI*2,d=90+R()*240,b=colony(NAMES[i],false,Math.cos(a)*d,Math.sin(a)*d,`hsl(${Math.floor(R()*360)} 75% 61%)`);if(i%4===0)addMass(b,3+Math.floor(R()*8));bots.push(b)}for(let i=0;i<100;i++)spawnFish();ranks=[];menu.hidden=true;results.hidden=true;hud.hidden=false;live=true;last=performance.now();requestAnimationFrame(frame)}
  function spawnFish(x=(R()-.5)*600,y=(R()-.5)*600,value=R()<.08?8:R()<.27?3:1){fish.push({x,y,value,spin:R()*6})}
  function addMass(c,n){c.fish+=n;while(n--)c.units.push(unit());let changed=true;while(changed){changed=false;for(const [from,to] of [[1,3],[3,9]]){let ids=[];c.units.forEach((u,i)=>u.tier===from&&ids.push(i));if(ids.length>=3){for(let i=2;i>=0;i--)c.units.splice(ids[i],1);c.units.push(unit(to));c.fusions++;changed=true;break}}}}
  function tick(c,dt){let boost=c.player?input.boost:false;if(c.player&&input.on)c.target=Math.atan2(input.y-c.y,input.x-c.x);if(!c.player&&time>c.think){c.think=time+c.brain;let target=fish.reduce((best,f)=>!best||dist(c,f)<dist(c,best)?f:best,null),enemy=[player,...bots].filter(o=>o!==c).sort((a,b)=>dist(c,a)-dist(c,b))[0];if(enemy&&dist(c,enemy)<70&&mass(c)>mass(enemy)*.75&&R()<.45)c.target=Math.atan2(enemy.y-c.y,enemy.x-c.x);else if(target)c.target=Math.atan2(target.y-c.y,target.x-c.x);if(Math.max(Math.abs(c.x),Math.abs(c.y))>290)c.target=Math.atan2(-c.y,-c.x);boost=R()<.12&&mass(c)>4}let da=Math.atan2(Math.sin(c.target-c.a),Math.cos(c.target-c.a));c.a+=clamp(da,-(boost?.055:.075)*dt*60,(boost?.055:.075)*dt*60);let speed=(boost?125:82)*dt;c.x=clamp(c.x+Math.cos(c.a)*speed,-310,310);c.y=clamp(c.y+Math.sin(c.a)*speed,-310,310);let last=c.trail[c.trail.length-1];if(dist(c,last)>.65){c.trail.push({x:c.x,y:c.y});if(c.trail.length>820)c.trail.shift()}}
  function crop(victim,index,attacker){if(time<victim.immune||victim.units.length<2)return;let cut=clamp(Math.floor(index/Math.max(1,victim.units.length)*victim.units.length),1,victim.units.length-1);let lost=victim.units.splice(cut);if(!lost.length)return;let value=lost.reduce((n,u)=>n+u.mass,0);victim.immune=time+1.25;attacker.crops+=value;attacker.big=Math.max(attacker.big,value);for(let n=value;n>0;){let value=n>=8?8:n>=3?3:1;spawnFish(victim.x+(R()-.5)*35,victim.y+(R()-.5)*35,value);n-=value}}
  function collisions(){let all=[player,...bots];for(const c of all){for(let i=fish.length-1;i>=0;i--)if(dist(c,fish[i])<15){addMass(c,fish[i].value);fish.splice(i,1);spawnFish()}for(const v of all)if(v!==c){let behind=0;for(let i=0;i<v.units.length;i++){behind+=v.units[i].space;let p=v.trail[Math.max(0,v.trail.length-1-Math.floor(behind/.65))];if(p&&Math.hypot(c.x-p.x,c.y-p.y)<12){crop(v,i,c);break}}}}}
  function drawPenguin(x,y,size,color,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle+Math.PI/2);ctx.fillStyle='#111827';ctx.beginPath();ctx.ellipse(0,0,size*.58,size*.75,0,0,7);ctx.fill();ctx.fillStyle='#edfaff';ctx.beginPath();ctx.ellipse(0,size*.15,size*.4,size*.48,0,0,7);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-size*.58,-size*.08,size*1.16,size*.13);ctx.fillStyle='#ff9d2d';ctx.beginPath();ctx.moveTo(0,-size*.7);ctx.lineTo(-size*.14,-size*.5);ctx.lineTo(size*.14,-size*.5);ctx.fill();ctx.restore()}
  function draw(){ctx.clearRect(0,0,w,h);let scale=Math.min(w,h)/720,cx=w/2-player.x*scale,cy=h/2-player.y*scale;ctx.save();ctx.translate(cx,cy);ctx.scale(scale,scale);ctx.fillStyle='#0b6e83';ctx.fillRect(-360,-360,720,720);ctx.strokeStyle='#75e3e4';ctx.globalAlpha=.22;ctx.lineWidth=2;for(let i=-300;i<350;i+=70){ctx.beginPath();ctx.moveTo(i,-340);ctx.lineTo(i+50,340);ctx.stroke()}ctx.globalAlpha=1;for(const f of fish){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(time+f.spin);ctx.fillStyle=f.value===8?'#ffd34e':f.value===3?'#ff8a46':'#ffb36e';ctx.beginPath();ctx.ellipse(0,0,f.value===8?8:5, f.value===8?5:3,0,0,7);ctx.fill();ctx.restore()}for(const c of [...bots,player]){let behind=0;for(let i=0;i<c.units.length;i++){behind+=c.units[i].space;let p=c.trail[Math.max(0,c.trail.length-1-Math.floor(behind/.65))];if(p)drawPenguin(p.x,p.y,c.units[i].tier===1?9:c.units[i].tier===3?12:16,c.color,c.a)}drawPenguin(c.x,c.y,15,c.color,c.a)}ctx.restore()}
  function updateHud(){ranks=[player,...bots].sort((a,b)=>mass(b)-mass(a));let rank=ranks.indexOf(player)+1;stats.textContent=`#${rank}  SCORE ${mass(player)*10+player.crops*15}\nMASS ${mass(player)}   ${Math.ceil(left)}s`;board.innerHTML='TOP WADDLES<br>'+ranks.slice(0,5).map((c,i)=>`${i+1}. ${c.name}  ${mass(c)}`).join('<br>')}
  function frame(now){if(!live)return;let dt=Math.min(.04,(now-last)/1000);last=now;time+=dt;left-=dt;for(const c of [player,...bots])tick(c,dt);collisions();draw();updateHud();if(left<=0)return finish();requestAnimationFrame(frame)}
  function finish(){live=false;hud.hidden=true;results.hidden=false;let rank=ranks.indexOf(player)+1,score=mass(player)*10+player.crops*15;summary.textContent=`RANK  #${rank}\nSCORE  ${score}\nMAX MASS  ${mass(player)}\nBIGGEST CROP  ${player.big}\nFISH COLLECTED  ${player.fish}\nFUSIONS  ${player.fusions}`}
  function steer(e){let r=canvas.getBoundingClientRect();input.x=(e.clientX-r.left-r.width/2)/Math.min(r.width,r.height)*720+player.x;input.y=(e.clientY-r.top-r.height/2)/Math.min(r.width,r.height)*720+player.y;input.on=true}
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);if(live)steer(e)});canvas.addEventListener('pointermove',e=>{if(live&&e.buttons)steer(e)});canvas.addEventListener('pointerup',()=>input.on=false);
  boostButton.addEventListener('pointerdown',e=>{e.preventDefault();input.boost=true});['pointerup','pointercancel','pointerleave'].forEach(n=>boostButton.addEventListener(n,()=>input.boost=false));
  play.onclick=reset;again.onclick=reset;home.onclick=()=>{results.hidden=true;menu.hidden=false};
  draw();
})();
